# Generated by Django 3.0.5 on 2020-04-02 19:20

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='textbox',
            field=tinymce.models.HTMLField(),
        ),
    ]
