# Generated by Django 3.0.4 on 2020-04-03 02:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_auto_20200402_1220'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Website',
            new_name='Entry',
        ),
    ]
