# Generated by Django 3.0.5 on 2020-04-05 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200404_1630'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
