# Generated by Django 3.0.5 on 2020-04-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200402_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='textbox',
            field=models.TextField(),
        ),
    ]
