# Generated by Django 3.0.5 on 2020-04-07 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200406_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 4, 7, 8, 35, 44, 736123)),
        ),
    ]
