# Generated by Django 3.0.4 on 2020-04-03 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200402_2107'),
        ('app', '0004_auto_20200402_2201'),
    ]

    operations = [
    ]
