# Generated by Django 3.0.5 on 2020-04-07 15:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200407_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='about',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
