# Generated by Django 3.0.5 on 2020-04-15 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_whitelistedemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordinance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('title', models.TextField()),
            ],
        ),
    ]
